name: singularity-hpc-test-registry

on:
  pull_request:
    types: [labeled]
    branches:
      - recipe/*

jobs:
  test-registry:
    if: ${{ github.event.label.name == 'container-recipe' }}
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: install Lmod
        run: |
            yum install -y epel-release && \
            yum update -y && \
            yum install -y lua lua-filesystem lua-posix wget gcc
            yum install -y Lmod singularity git

      - name: Derive number of commits
        run: |
            cd /opt
            branch=$(echo ${GITHUB_REF#refs/heads/})
            echo $branch
            git clone -b main https://github.com/singularityhub/singularity-hpc
            cd singularity-hpc
            git checkout -b $branch
            git pull origin $branch
            commits=$(git rev-list --count main)
            echo "Found $commits since main"
            cd registry
            touch changes.txt
            for container_yaml in $(git diff --name-only HEAD~$commits..HEAD .); do
                echo $container_yaml >> changes.txt
            done
            cat changes.txt

      - name: Update .bashrc
        run: |
          echo ". /usr/share/lmod/lmod/init/sh" >> $HOME/.bashrc

      - name: Check .bashrc
        run: |
          cat $HOME/.bashrc

      - name: Save changelist
        uses: actions/upload-artifact@v2
        with:
          name: changes.txt
          path: /opt/singularity-hpc/registry/changes.txt

      - name: Install conda
        run: |
          CONDA_SCRIPT=Miniconda3-latest-Linux-x86_64.sh
          wget https://repo.anaconda.com/miniconda/$CONDA_SCRIPT
          /bin/bash $CONDA_SCRIPT -b -p /usr/share/miniconda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create --quiet --name shpc -c conda-forge spython

      - uses: actions/checkout@v2
      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install -e .

      - name: Download changelist
        uses: actions/download-artifact@v2
        with:
          name: changes.txt

      - name: Run module tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"

          source activate shpc
          cd registry
          for container_yaml in $(cat ../changes.txt); do
              module=$(dirname $container_yaml)
              module=$(echo "${module/registry\//}")
              echo "Testing $module"
              shpc test --template ../shpc/tests/test-registry-module.sh $module
              # TODO test adding tests when this works
          done
