name: shpc docs

on:
  push:
    branches: [disabled]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Create conda environment
      run: conda create --quiet -c conda-forge --name shpc spython

    - name: Install shpc
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        root=$PWD
        source activate shpc
        cd /tmp
        git clone https://github.com/singularityhub/singularity-hpc
        cd singularity-hpc
        pip install -e .
        cd $root

    - name: Generate docs
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate shpc
        /bin/bash generate.sh

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # v4.4.1
      with:
        branch: gh-pages
        folder: .
