name: singularity-hpc-test-registry

on:
  # TODO: update this to be binoc updates
  pull_request:
    branches_ignore: []

jobs:
  test-registry:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v1
      - name: install Lmod
        run: |
            yum install -y epel-release && \
            yum update -y && \
            yum install -y lua lua-filesystem lua-posix wget gcc
            yum install -y Lmod singularity

      - name: Install conda
        run: |
          CONDA_SCRIPT=Miniconda3-latest-Linux-x86_64.sh
          wget https://repo.anaconda.com/miniconda/$CONDA_SCRIPT
          /bin/bash $CONDA_SCRIPT -b -p /usr/share/miniconda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create --quiet --name shpc -c conda-forge spython

      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install -e .

      - name: Run module tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc

          # Test each module file that is changed (there should be just one commit)
          cd registry
          for container_yaml in $(git diff --name-only HEAD .); do
              module=$(dirname $container_yaml)
              module=$(echo "${module/registry\//}")
              echo "Testing $module"
              shpc test $module
              # TODO test adding tests when this works
          done
