name: singularity-hpc-test-registry

on:
  pull_request:
    branches_ignore: []

jobs:
  test-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup black linter
        run: conda create --quiet --name shpc -c conda-forge spython

      - name: install dependencies Linux
        run: sudo apt install tcsh tcl tcl-dev uuid r-base r-base-dev cmake fish tclsh zsh
      - name: set up lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.4"
      - name: install luarocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: install lua dependencies
        run: |
          luarocks install luaposix
          luarocks install luafileSystem
          luarocks install luajson
          luarocks install lua-term
          which module

      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install -e .
          cd registry

          for module in $(shpc show --versions| sort); do
              shpc check $module
              echo $?
          done

