name: test-update

on:
  # Run on any push to a binoc branch, which is a container recipe update
  push:
    branches:
      - binoc/**

jobs:
  test-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install lua5.2 liblua5.2-dev lua-filesystem lua-posix tcl tcl-dev

      - name: Install LMOD
        run: |
          PKG_VERSION=8.4.27
          PKG_URL="https://github.com/TACC/Lmod/archive/${PKG_VERSION}.tar.gz"
          wget $PKG_URL
          tar xfz ${PKG_VERSION}.tar.gz
          cd Lmod-${PKG_VERSION}
          ./configure --prefix=/usr/share && make && make install

      - uses: eWaterCycle/setup-singularity@v6
        name: Install Singularity
        with:
          singularity-version: 3.6.4

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name shpc spython

      - uses: actions/checkout@v2
      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install -e .

      - name: Run module tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"

          source activate shpc
          cd registry

          # There should only be one commit with changes.
          for container_yaml in $(git diff --name-only HEAD~1..main .); do
              module=$(dirname $container_yaml)
              module=$(echo "${module/registry\//}")
              echo "Testing $module"
              shpc test --template ../shpc/tests/test-registry-module.sh --commands $module
          done
